# Sample AWS machine class

apiVersion: cluster.k8s.io/v1alpha1
kind: MachineClass
metadata:
  name: test-aws
  namespace: default
providerConfig:
  spec:         # Will be removed in future
    ami: ami-123456 # Amazon machine image name goes here
    region: eu-east-1 # Region in which machine is to be deployed
    machineType: t2.large # Type of ec2 machine
    iam:
      name: iam-name # Name of the AWS Identity and Access Management
    keyName: key-value-pair-name # EC2 keypair used to access ec2 machine
    networkInterfaces:
      - subnetID: subnet-acbd1234 # The subnetID in which machine is to be deployed
        securityGroupIDs: ["sg-xyz12345"] # The security groups to which it is attached to
    tags:
      Name: sample-machine-name # Name tag that can be used to identify a machine at AWS
      kubernetes.io/cluster/****: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller. Replace **** string with your desired cluster name.
      kubernetes.io/role/****: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by by this controller. Replace **** string with your desired role name.
      tag1: tag1-value # A set of additional tags attached to a machine (optional)
      tag2: tag2-value # A set of additional tags attached to a machine (optional)
    blockDevices:
      - ebs:
          volumeSize: 50  # Size of the root block device
          volumeType: gp2 # Type of the root block device
secretRef: # Secret pointing to a secret which contains the provider secret and cloudconfig
  namespace: default  # Namespace
  name: test-secret # Name of the secret
provider: AWS
