# Sample machine object
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  name: test-machine # Name of the machine to be created
  namespace: default
  labels:
    test-label: test-label # Label used by machine-set to match (optional)
spec:
  providerConfig:
    valueFrom:
      machineClass: 
        kind: AWS
        name: test-aws
